# Eigenvectors and Eigenvalues

In [1]:
import numpy as np
from scipy import linalg

### Computing Eigenvalues and Eigenvectors
-  Compute eigenvalues and eigenvectors for the matrix  $A = \begin{bmatrix} -1 & 3 \\ 2 & 0 \end{bmatrix}$ and its square $A^2 = \begin{bmatrix} 7 & -3 \\ -2 & 6 \end{bmatrix}$

In [2]:
# 2x2 Matrix
A = np.array([[-1,3], [2,0]])
A

array([[-1,  3],
       [ 2,  0]])

In [3]:
# Square of A
A2 = np.linalg.matrix_power(A,2)
A2

array([[ 7, -3],
       [-2,  6]])

In [4]:
# Eigenvalues and Eigenvectors of Matrix A
w, v = np.linalg.eig(A)

In [5]:
# Eigenvalues
w

array([-3.,  2.])

In [6]:
# Eigenvectors
v

array([[-0.83205029, -0.70710678],
       [ 0.5547002 , -0.70710678]])

In [7]:
# Eigenvalues and Eigenvectors of Matrix A2
w2, v2 = np.linalg.eig(A2)

In [8]:
w2

array([9., 4.])

In [9]:
v2

array([[ 0.83205029,  0.70710678],
       [-0.5547002 ,  0.70710678]])

- When Matrix $A$ has eigenvalues $λ_1$ and $λ_2$, $A^2$ has eigenvalues $λ_1^2$ and $λ_2^2$
- Eigenvectors of Matrix $A$ and Matrix $A^2$ are the same

---

### Computing Eigenvalues of Matrix and its Inverse
- Compute the eigenvalues of matrix $A = \begin{bmatrix} 0 & 2 \\ 2 & 3 \end{bmatrix}$ and its inverse $A^- = \begin{bmatrix} \frac{-3}{4} & \frac{1}{2} \\ \frac{1}{2} & 0 \end{bmatrix}$

In [10]:
# 2x2 Matrix
A = np.array([[0,2], [2,3]])
A

array([[0, 2],
       [2, 3]])

In [11]:
# Inverse of A
A_inv = np.linalg.inv(A)
A_inv

array([[-0.75,  0.5 ],
       [ 0.5 ,  0.  ]])

In [12]:
# Eigenvalues and Eigenvectors of Matrix A
w, v = np.linalg.eig(A)

In [13]:
# Eigenvalues
w

array([-1.,  4.])

In [14]:
# Eigenvector
v

array([[-0.89442719, -0.4472136 ],
       [ 0.4472136 , -0.89442719]])

In [15]:
# Eigenvalues and Eigenvectors of Matrix A inverse
w_inv, v_inv = np.linalg.eig(A_inv)

In [16]:
# Eigenvalues
w_inv

array([-1.  ,  0.25])

In [17]:
# Eigenvector
v_inv

array([[-0.89442719, -0.4472136 ],
       [ 0.4472136 , -0.89442719]])

- If Matrix $A$ has eigenvalues $λ_1$ and $λ_2$, then its inverse Matrix $A^-$  has eigenvalues $\frac{1}{λ_1}$ and $\frac{1}{λ_2} $
- Eigenvectors of Matrix $A$ and Matrix $A^-$ are the same

---

### Change of Basis
- Let $B$ be an ordered basis for $R^2$ and linear transformation to be *Identity Transformation* $L(v) = v$ from old basis $B$ to new basis $C$
- If $B = \begin{bmatrix} 1 & 1 \\ 1 & 0 \end{bmatrix}$, new basis $C = \begin{bmatrix} 1 & 1 \\ 1 & 0 \end{bmatrix}$