In [11]:
import numpy as np
from scipy import linalg
import sympy as sympy
from sympy import *

---

# Matrix Properties

### Inverse and Determinants

- The $n \times n$ Matrix $A$ is **Invertible** and **Non-Singular** if there exists a Matrix $B$ such that $AB = BA = I$
- The **Determinant** is a scalar value that indicates the scale of the transformation
- If Matrix $A$ is **Invertable**, then Matrix $A \begin{bmatrix} a & d \\ b & c \end{bmatrix}$ is **Non-Singular**, and $ab - cd \neq 0$
- If Matrix $A$ is **Non-Invertable**, then Matrix $A \begin{bmatrix} a & d \\ b & c \end{bmatrix}$ is **Singular**, and $ab - cd = 0$
- If Matricies $A$ and $B$ are Invertible $n \times n$ Matricies, then $(AB)^{-1} = B^{-1}A^{-1}$

### Matrix Transpose

- Find Matrix $(AB)^{T}$ if $A = \begin{bmatrix} 1 & 3 \\ 2 & 4 \end{bmatrix}$ and $B = \begin{bmatrix} 6 & 0 \\ -2 & 7 \end{bmatrix}$
- $(AB)^{T} \neq A^{T} B^{T}$

In [4]:
A = np.array([[1,3], [2,4]])
B = np.array([[6,0], [-2,7]])

In [5]:
# Find Transpose of A*B
np.transpose(np.dot(A,B))

array([[ 0,  4],
       [21, 28]])

In [6]:
# Dot Product of A.transpose() and B.transpose()
np.dot(A.transpose(), B.transpose())

array([[ 6, 12],
       [18, 22]])

- $(AB)^{T} \neq A^{T} B^{T}$

---

# Linear Systems

### Augmented Matrix Notation and Elimination Algorithm:
- Forward prop for every row:
    - Make the leftmost nonzero entry in the top row 1 by multiplication
    - Use that to eliminate everything below it
    - Make the leftmost nonzero entry in the next row 1
    - Use that to eliminate everything below it
    - Go to the next row and repeat...
- Back prop:
    - In the column that contains leftmost entry 1, eliminate entries above it and make them zero
    
### Elementary Row Operations:
- Row swap
- Scalar Multiplication
- Row Addition

### Pivots and Free Variables:
- In every row the leftmost non-zero entry 1 is called a pivot
- Variables corresponding to the columns that do not contain the pivot are called Free Variables

### RREF: Reduced Row Echelon Form

- Use elementary row operations to find the RREF for Matrix $A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix}$

In [22]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Transform NumPy array into a Sympy Matrix
M = sympy.Matrix(A)
print(f"Matrix : {M} ") 
   
# Use sympy.rref() method  
M_rref = M.rref()
print(f"Matrix : {M_rref} ") 

Matrix : Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
Matrix : (Matrix([
[1, 0, -1],
[0, 1,  2],
[0, 0,  0]]), (0, 1)) 


### Solvability and Rank of a Matrix:
- Gaussian elimination reveals the **Pivot Variables** and **Free Variables** of a Matrix
- If there are **r** Pivots, then there are **n - r** Free Variables
- The **Rank of a Matrix, rank(A)** is equal to the number of **Pivot Variables** 

In [25]:
# Find the Rank of Matrix A
A = np.array([[1,2,3],[1,4,9],[1,8,27]])

# Find Rank using np.linalg.matrix_rank(A)
np.linalg.matrix_rank(A)

3

In [26]:
# Find Rank with RREF, using sympy.rref() method
M = sympy.Matrix(A)
M_rref = M.rref()
print(f"Matrix : {M_rref} ") 

Matrix : (Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]]), (0, 1, 2)) 


- 3 Pivots indicate Rank(A) = 3

In [24]:
# 1) Wrong result
A = np.array([[2,-4,-1], [1,-3,1], [3,-5,-3]])
A = np.matrix(A)
b = np.array([1,1,1])
print("A: "); print(A)
print("b: "); print(b)

A_inverse = np.linalg.inv(A) # find inverse of X
print("A_inverse: "); print(A_inverse)

X = np.dot(A_inverse, b)
print("X: "); print(X)

A: 
[[ 2 -4 -1]
 [ 1 -3  1]
 [ 3 -5 -3]]
b: 
[1 1 1]
A_inverse: 
[[-1.57625987e+16  7.88129935e+15  7.88129935e+15]
 [-6.75539944e+15  3.37769972e+15  3.37769972e+15]
 [-4.50359963e+15  2.25179981e+15  2.25179981e+15]]
X: 
[[0.  0.  0.5]]


In [30]:
# 1) Second try 
A = np.array([[2,-4,-1], [1,-3,1], [3,-5,-3]])
print("A: "); print(A)
b = np.array([1,1,1])
print("b: "); print(b)
X = np.linalg.solve(A, b)
print("X: "); print(X)

# Check that the solution is correct:
np.allclose(np.dot(A, X), b)


A: 
[[ 2 -4 -1]
 [ 1 -3  1]
 [ 3 -5 -3]]
b: 
[1 1 1]
X: 
[ 0.375 -0.125  0.25 ]


True

In [9]:
# 2) Dot product of u*v

u = np.array([3,1,4])
v = np.array([2,2,-4])

np.dot(u,v)

-8

In [12]:
# 3) Is A invertible

A = np.array([[-1,2], [3,-6]])
np.linalg.inv(A) # False

LinAlgError: Singular matrix

In [20]:
# 4) A^3

A_array = np.array([[3,1], [2,1]])
A_array3 = np.linalg.matrix_power(A_array, 3)
print(A_array)
print(A_array3)

A_matrix = np.matrix(A_array)
A_matrix3 = A_matrix**3
print(A_matrix)
print(A_matrix3)

[[3 1]
 [2 1]]
[[41 15]
 [30 11]]
[[3 1]
 [2 1]]
[[41 15]
 [30 11]]
