In [11]:
import numpy as np
from scipy import linalg
import sympy as sympy
from sympy import *

---

# Matrix Properties

### Inverse and Determinants

- The $n \times n$ Matrix $A$ is **Invertible** and **Non-Singular** if there exists a Matrix $B$ such that $AB = BA = I$
- The **Determinant** is a scalar value that indicates the scale of the transformation
- If Matrix $A$ is **Invertable**, then Matrix $A \begin{bmatrix} a & d \\ b & c \end{bmatrix}$ is **Non-Singular**, and $ab - cd \neq 0$
- If Matrix $A$ is **Non-Invertable**, then Matrix $A \begin{bmatrix} a & d \\ b & c \end{bmatrix}$ is **Singular**, and $ab - cd = 0$
- If Matricies $A$ and $B$ are Invertible $n \times n$ Matricies, then $(AB)^{-1} = B^{-1}A^{-1}$

### Matrix Transpose

- Find Matrix $(AB)^{T}$ if $A = \begin{bmatrix} 1 & 3 \\ 2 & 4 \end{bmatrix}$ and $B = \begin{bmatrix} 6 & 0 \\ -2 & 7 \end{bmatrix}$
- $(AB)^{T} \neq A^{T} B^{T}$

In [4]:
A = np.array([[1,3], [2,4]])
B = np.array([[6,0], [-2,7]])

In [5]:
# Find Transpose of A*B
np.transpose(np.dot(A,B))

array([[ 0,  4],
       [21, 28]])

In [6]:
# Dot Product of A.transpose() and B.transpose()
np.dot(A.transpose(), B.transpose())

array([[ 6, 12],
       [18, 22]])

- $(AB)^{T} \neq A^{T} B^{T}$

---

# Linear Systems

### Augmented Matrix Notation and Elimination Algorithm:
- Forward prop for every row:
    - Make the leftmost nonzero entry in the top row 1 by multiplication
    - Use that to eliminate everything below it
    - Make the leftmost nonzero entry in the next row 1
    - Use that to eliminate everything below it
    - Go to the next row and repeat...
- Back prop:
    - In the column that contains leftmost entry 1, eliminate entries above it and make them zero
    
### Elementary Row Operations:
- Row swap
- Scalar Multiplication
- Row Addition

### Pivots and Free Variables:
- In every row the leftmost non-zero entry 1 is called a pivot
- Variables corresponding to the columns that do not contain the pivot are called Free Variables

### RREF: Reduced Row Echelon Form

- Use elementary row operations to find the RREF for Matrix $A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix}$

In [22]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Transform NumPy array into a Sympy Matrix
M = sympy.Matrix(A)
print(f"Matrix : {M} ") 
   
# Use sympy.rref() method  
M_rref = M.rref()
print(f"Matrix : {M_rref} ") 

Matrix : Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
Matrix : (Matrix([
[1, 0, -1],
[0, 1,  2],
[0, 0,  0]]), (0, 1)) 


### Rank of a Matrix:
- Gaussian elimination reveals the **Pivot Variables** and **Free Variables** of a Matrix
- If there are **r** Pivots, then there are **n - r** Free Variables
- The **Rank of a Matrix, rank(A)** is equal to the number of **Pivot Variables** 

In [25]:
# Find the Rank of Matrix A
A = np.array([[1,2,3],[1,4,9],[1,8,27]])

# Find Rank using np.linalg.matrix_rank(A)
np.linalg.matrix_rank(A)

3

In [26]:
# Find Rank with RREF, using sympy.rref() method
M = sympy.Matrix(A)
M_rref = M.rref()
print(f"Matrix : {M_rref} ") 

Matrix : (Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]]), (0, 1, 2)) 


- 3 Pivots indicate Rank(A) = 3

### Solvability and Rank of a Matrix:
- Full Column rank:
    - For mxn Matrix A, if n<m, rank(A) = n, and there is zero or one solutions
- Full Row rank:
    - For mxn Matrix A, if m<n, rank(A) = m, and there is always a solution (infinite numner)
- Full rank:
    - For mxn Matrix A, if m=n, rank(A) = m = n, and there is only one unique solution, Matrix is Invertible
- Not Full rank:
    - For mxn Matrix A, if m=n, rank(A) < {m,n}, and there is zero or infinitelly manu solutions

### Solution Set:
- **Non-Homogenoues System** or **Particular**: $Ax_{p}  = b$
    - If Matrix A is an $n \times n$ Matrix and has a rank of $n$, then the system $Ax = b$ has a unique solution, and RREF of A is the Identity Matrix $I$
- **Homogenoues System**: $Ax_{h} = 0$
    - Trivial solution to a homogenous system is $x = 0$, but there may be infinitely many solutions, when there are more unknowns than equations
    - If Matrix A is a square Matrix $n \times n$, and $Ax = 0$ has only trivial solution $x = 0$, then the Rank(A) is $n$
- **Complete Soluton** is a set of solutions: $x = x_{p} + x_{h}$
- $A(x_{p} + x_{h}) = Ax_{p} + Ax_{h} = b + 0 = b$

---

# Vector Spaces

### Vectors:
- Vector $v$ in space $R^{n}$ is denotes as $v = (v_{1}, v_{2}, ... , v_{n})$
- $0$ is a Zero Vector
- Vector Space: Vectors that are subject to Vector Addition and Multiplication
- Subspace: A Subset $W$of a Vector Space $V$ is called a **subspace** of $V$ if $W$ is itself a Vector Space under addition and scalar multiplication difined in $V$

### Span:
- **Linear Combination** of some set of vectors $(v_{1}, v_{2}, ... , v_{n})$ is given by multiplying each vector by a corresponding scalar coefficient and adding the results: $\Sigma_{i} c_{i}v_{i}$
- The subspace of a Vector Space formed by all possible combinations of the vectors in the non-empty set of Vectors $S$, is called the **Span of $S$** and the Vectors in $S$ **span the subspace $S$**
- **Span(S)** = span$(v_{1}, v_{2}, ... , v_{n})$
- Span{v} in $R^{3}$ is a **Line** that contains $v$ and the  origin
- Span{u,v} in $R^{3}$ is a **Plain** that contains $u, v$ and the origin

# Eigenvectors and Eigenvalues

In [28]:
# Find the Eigenvectors of Matix A
A = np.array([[2,1],[3,0]])

# Eigenvalues (w) and Eigenvectors (v) of Matrix A
w, v = np.linalg.eig(A)
print(f"Eigenvalues are: \n {w}")
print(f"Eigenvectors are: \n {v}")

Eigenvalues are: 
 [ 3. -1.]
Eigenvectors are: 
 [[ 0.70710678 -0.31622777]
 [ 0.70710678  0.9486833 ]]


# Single Value Decomposition