# Singular Value Decomposition: SVD

## $$A = U \Sigma V^T$$

In [1]:
import numpy as np
from scipy import linalg

### Using NumPy built-in *svd* function

In [2]:
def builtin_svd(A):
    
    # Get the shape of a passed in Matrix A
    m,n = A.shape
    
    # Compute SVD,and convert array of singular values into a Matrix
    U,s,Vh = np.linalg.svd(A)
    S = linalg.diagsvd(s,m,n)
    
    return U, S, Vh

---

### Reconstruct SVD based on the following:
- $U$ - left singular vectors of Matrix $A$: set of orthonormal eigenvectors of $AA^T$
- $V^T$ - right singular vectors of Matrix $A$: set of orthonormal eigenvectors of $A^TA$
- $\Sigma$ - diagonal non-zero singular values of $A$: square roots of the non-zero eigenvalues of $AA^T$ or $A^TA$

In [64]:
def manual_svd(A):
    
    # Get the shape of a passed in Matrix A
    m,n = A.shape
    
    # Find V: right singular vector
    AA_t = np.dot(A.T, A)
    V_la, V = np.linalg.eig(AA_t)
    Vh = V.T
    
    # Find Sigma by sorting eigenvalues in descending order and taking square root
    V_la[::-1].sort()
    sig = np.sqrt(V_la)
    S = linalg.diagsvd(sig, m, n)
    
    # Find U: left singular vector
    A_tA = np.dot(A,A.T)
    U_la, U = np.linalg.eig(A_tA)
    
    return U, S, Vh

---

In [78]:
# Matrix A
A = np.array([[1,0], [0,1], [-1,0]])
A

array([[ 1,  0],
       [ 0,  1],
       [-1,  0]])

#### Check using built-in SVD 

In [79]:
U,S,Vh = builtin_svd(A)
U,S,Vh

(array([[-0.70710678,  0.        ,  0.70710678],
        [ 0.        ,  1.        ,  0.        ],
        [ 0.70710678,  0.        ,  0.70710678]]),
 array([[1.41421356, 0.        ],
        [0.        , 1.        ],
        [0.        , 0.        ]]),
 array([[-1., -0.],
        [ 0.,  1.]]))

In [80]:
# Check for A
np.dot(U, np.dot(S,Vh))

array([[ 1.,  0.],
       [ 0.,  1.],
       [-1.,  0.]])

#### Check with munual SVD

In [81]:
U,S,Vh = manual_svd(A)
U,S,Vh

(array([[ 0.70710678,  0.70710678,  0.        ],
        [ 0.        ,  0.        ,  1.        ],
        [-0.70710678,  0.70710678,  0.        ]]),
 array([[1.41421356, 0.        ],
        [0.        , 1.        ],
        [0.        , 0.        ]]),
 array([[1., 0.],
        [0., 1.]]))

In [82]:
# Check for A
np.dot(U, np.dot(S,Vh))

array([[ 1.        ,  0.70710678],
       [ 0.        ,  0.        ],
       [-1.        ,  0.70710678]])

In [83]:
U,s,Vh = np.linalg.svd(A)
U,s,Vh

(array([[-0.70710678,  0.        ,  0.70710678],
        [ 0.        ,  1.        ,  0.        ],
        [ 0.70710678,  0.        ,  0.70710678]]),
 array([1.41421356, 1.        ]),
 array([[-1., -0.],
        [ 0.,  1.]]))

---