# Vector Spaces

In [2]:
import numpy as np
from scipy import linalg
from sympy import * 

### Subspaces
- Find dimensions of 4 subspaces if Null space of a 2x3 Matrix: $$A \begin{bmatrix}1 & 0 & 0 \\ 0 & 1 & 0\end{bmatrix} = 1$$

In [3]:
# 2x3 Matrix
A = np.array([[1,0,0], [0,1,0]])
A

array([[1, 0, 0],
       [0, 1, 0]])

In [4]:
# Column space dimension = Rank of Matrix A = 2
np.linalg.matrix_rank(A)

2

In [5]:
# Null space dimension of N(A) = n – r = 3 - 2 = 1
linalg.null_space(A)

array([[0.],
       [0.],
       [1.]])

In [6]:
# Row space dimension = Column space of Transpose(A) = r = 2
np.linalg.matrix_rank(A.transpose())

2

In [7]:
# Left Null space = Null space of Transpose(A) = m - r = 2 – 2 = 0
linalg.null_space(A.transpose())

array([], shape=(2, 0), dtype=float64)

---

### Null Space
- Find out if Vectors $u \begin{bmatrix}-3 \\ 1 \\ 1\end{bmatrix}$ and $v \begin{bmatrix}-2 \\ 1 \\ 0\end{bmatrix}$  are in the Null space of a Matrix $\begin{bmatrix}1 & 2 & 1 \\ 3 & 6 & 4\end{bmatrix}$

In [8]:
import numpy as np
from scipy import linalg

In [9]:
# Are Vectors u and v in Null Space of Matrix A, Null(A)?
A = np.array([[1,2,1], [3,6,4]])
u = np.array([-3,1,1])
v = np.array([-2,1,0])

In [10]:
# For a Vector to be in Null(A), Ax=0
np.dot(A,u)

array([0, 1])

In [11]:
# For a Vector to be in Null(A), Ax=0
np.dot(A,v)

array([0, 0])

- $A \cdot v = 0$, Vector $v$ is in the Null space of $A$
- $A \cdot u \neq 0$, Vector $u$ is not in the Null space of $A$

---

### Column Space
- Find out if Vectors $a \begin{bmatrix}2 \\ 3 \\ -7 \\ 3 \end{bmatrix}$ , $b \begin{bmatrix} 0 \\ 0 \\ 0\\ 0 \end{bmatrix}$ , $ c \begin{bmatrix} 1 \\ 1 \\ 1 \\ 1 \end{bmatrix}$ are in the Column Span of a Matrix $ A \begin{bmatrix}2 & 3 & -1 \\ 1 & -1 & 0 \\ 0 & 5 & 2 \\ 3 & 2 & 1 \end{bmatrix}$

In [12]:
A = np.array([[2,3,-1], [1,-1,0],[0,5,2],[3,2,1]])
a = np.array([2,3,-7,3])
b = np.array([0,0,0,0])
c = np.array([1,1,1,1])

- Vector $a$ is in the range if and only if there exists some Vector $x$ such that $A \cdot x = a$
- To find $x$, solve linear system
- Can't solve with np.linalg.solve(A, c), since Matrix $A$ is not square.  
- Solve by getting RREF using SymPy

In [13]:
# Add the vector to Matrix A and use sympy.rref() method to calculate RREF
Aa_rref = Matrix(np.append(A,a.reshape(4,1), axis=1)).rref()  
Aa_rref

(Matrix([
 [1, 0, 0,  2],
 [0, 1, 0, -1],
 [0, 0, 1, -1],
 [0, 0, 0,  0]]),
 (0, 1, 2))

In [14]:
# Add the vector to Matrix A and use sympy.rref() method to calculate RREF
Ab_rref = Matrix(np.append(A,b.reshape(4,1), axis=1)).rref()  
Ab_rref

(Matrix([
 [1, 0, 0, 0],
 [0, 1, 0, 0],
 [0, 0, 1, 0],
 [0, 0, 0, 0]]),
 (0, 1, 2))

In [15]:
# Add the vector to Matrix A and use sympy.rref() method to calculate RREF
Ac_rref = Matrix(np.append(A,c.reshape(4,1), axis=1)).rref()  
Ac_rref

(Matrix([
 [1, 0, 0, 0],
 [0, 1, 0, 0],
 [0, 0, 1, 0],
 [0, 0, 0, 1]]),
 (0, 1, 2, 3))

- Since $0 \neq 1$, Vector $c$ is not in Column Space of Matrix $A$

---

### Orthogonal Vectors
- Find out if Vectors $u \begin{bmatrix} -2 \\ 3 \\ 1 \\ 4 \end{bmatrix}$ , and $ v \begin{bmatrix} 1 \\ 2 \\ 0\\ -1 \end{bmatrix}$ are orthogonal in Vector Space

In [16]:
u = np.array([-2,3,1,4])
v = np.array([1,2,0,-1])

In [17]:
# Vectors u and v are orthogonal (or perpendicular) to each other if, u*v = 0
np.dot(u,v)

0

- Since the dot product of $u \cdot v \neq 0$, vectors are orthogonal

---