# Creating NumPy Arrays

In [56]:
import numpy as np

## Using array Method - supply a list or list of lists

#### 1-D Array

In [57]:
a = np.array([3,6,9])
a

array([3, 6, 9])

#### 2-D Array

In [58]:
b = np.array([ [3,6,9], [2,4,6] ])
b

array([[3, 6, 9],
       [2, 4, 6]])

## Using zeros() and ones() Method 

#### Create array of zeros as placeholder

In [59]:
#2-D array of 5 rows and 3 columns
c = np.zeros((5,3))
c

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [60]:
c.dtype

dtype('float64')

#### Create array of ones as placeholder.

In [61]:
#2-D array of 1s, 3 rows and 2 columns
d = np.ones((3,2))
d

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [62]:
d.dtype.name

'float64'

#### Creates array of 2s as placeholder.

In [63]:
e = np.ones((3,2)) + 1
e

array([[ 2.,  2.],
       [ 2.,  2.],
       [ 2.,  2.]])

## Specify Data type

In [64]:
f = np.ones((3,4), dtype=np.int64)
f

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)

#### Float Data Type 

In [65]:
f2 = np.array([1,2,3], dtype=float)
f2

array([ 1.,  2.,  3.])

In [66]:
f3 = np.ones((3,4), dtype=float)
f3

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

#### Complex Data Type

In [83]:
f4 = np.array([1+2j, 3+4j, 5+6*1j])
f4

array([ 1.+2.j,  3.+4.j,  5.+6.j])

In [84]:
f4.dtype

dtype('complex128')

#### Boolean Data Types

In [90]:
f5 = np.array([True, False, True])
f5

array([ True, False,  True], dtype=bool)

In [91]:
f5.dtype

dtype('bool')

#### String Data Type

In [92]:
f6 = np.array(['Bonjour', 'Hello', 'Holla'])
f6

array(['Bonjour', 'Hello', 'Holla'], 
      dtype='<U7')

In [93]:
f6.dtype

dtype('<U7')

## Using empty function - random numbers close to 0

In [94]:
g = np.empty((4,4))
g

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [95]:
g.dtype.name

'float64'

## Random Arrays

In [96]:
random1 = np.random.rand(4) #random number from 0 to 1, uniform
random1

array([ 0.48454851,  0.52386136,  0.54027637,  0.60398586])

In [97]:
random2 = np.random.randn(4) #random number from 0 to 1, Gaussian
random2

array([ 1.9123435 , -0.00744689,  1.80483972,  0.36547241])

## Using arange function

#### 1-D Array from 0 to 10, increamented by 2 

In [99]:
h = np.arange(0,10,2)
h

array([0, 2, 4, 6, 8])

## Using arange with reshape functions

In [101]:
m = np.arange(10)
m

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Reshape into 5x2 matrix

In [102]:
m2 = np.arange(10).reshape(5,2)
m2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

## Using linspace function

#### Array from 0 to 5 with 13 points (inclusive)

In [103]:
k = np.linspace(0,5,13)
k

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ])

#### Array from 0 to 5 with 13 points (exclusive)

In [104]:
#Will not reach endpoint, but still 13 elements
k2 = np.linspace(0,5,13, endpoint=False) 
k2

array([ 0.        ,  0.38461538,  0.76923077,  1.15384615,  1.53846154,
        1.92307692,  2.30769231,  2.69230769,  3.07692308,  3.46153846,
        3.84615385,  4.23076923,  4.61538462])

## Making Array of Complex numbers

In [105]:
complexMatrix = np.array([ [2,4], [3,6], [4,8] ], dtype=complex)
complexMatrix

array([[ 2.+0.j,  4.+0.j],
       [ 3.+0.j,  6.+0.j],
       [ 4.+0.j,  8.+0.j]])

In [106]:
complexMatrix.dtype

dtype('complex128')

## Other types: Boolean, String

In [107]:
bool_array = np.array([True, False, True])
bool_array

array([ True, False,  True], dtype=bool)

In [108]:
string_array = np.array(['Bonjour', 'Hello', 'Holla'])
string_array

array(['Bonjour', 'Hello', 'Holla'], 
      dtype='<U7')

## Diagnol Arrays - Using eyes and diag

#### 3x3 array of diognal 1s -> Float

In [110]:
diag1 = np.eye(3) 
diag1

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

#### 3x3 array of diognal 1s -> Integers

In [111]:
diag2 = np.diag(np.array([1,1,1])) 
diag2

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [112]:
diag3 = np.diag(np.array([1,2,3,4])) 
diag3

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])