# NumPy - Array Shapes Manipulation

In [1]:
import numpy as np

## Shape with np.newaxis

In [2]:
a = np.arange(0,40,10)
a.shape

(4,)

#### Transform into 2-D Array

In [3]:
#All but each starting on new axis
a = a[:, np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [4]:
a.shape

(4, 1)

#### Using reshape need to know number of elements for rows, not the case with np.newaxis

In [5]:
a2 = np.arange(0,40,10).reshape(4,1)
a2

array([[ 0],
       [10],
       [20],
       [30]])

#### Example of Broadcasting

In [6]:
b = np.array([0,1,2])
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

## Flatten

In [7]:
c = np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

#### ravel() - Flattens the array but does NOT manipulate original Array

In [8]:
c.ravel()

array([1, 2, 3, 4, 5, 6])

In [9]:
c

array([[1, 2, 3],
       [4, 5, 6]])

#### Transpose() Does NOT manipulate original Array

In [10]:
#Does NOT manipulate original Array
c.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [11]:
c.T.ravel()

array([1, 4, 2, 5, 3, 6])

#### Original Array stays the same

In [12]:
c

array([[1, 2, 3],
       [4, 5, 6]])

## Reshape

In [13]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
c.shape

(2, 3)

#### Flatten and assign to new Array as a VIEW

In [15]:
d = c.ravel()
d

array([1, 2, 3, 4, 5, 6])

#### Reshape the VIEW into 3x2, Original Array will stay the same

In [16]:
d = d.reshape((3,2))
d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
#c shape stays the same
c.shape

(2, 3)

In [18]:
#d has its own shape now
d.shape

(3, 2)

In [19]:
#But d is still a VIEW of c
d[1,0] = 99
d

array([[ 1,  2],
       [99,  4],
       [ 5,  6]])

In [20]:
c

array([[ 1,  2, 99],
       [ 4,  5,  6]])

## Use copy() to assign a copy NOT a View

In [21]:
e = np.copy(c.ravel())
e

array([ 1,  2, 99,  4,  5,  6])

In [22]:
e = e.reshape((3,2))
e

array([[ 1,  2],
       [99,  4],
       [ 5,  6]])

In [23]:
e[1,0] = 55
e

array([[ 1,  2],
       [55,  4],
       [ 5,  6]])

#### Now Original Array Does NOT Change

In [24]:
#c Does NOT change now
c

array([[ 1,  2, 99],
       [ 4,  5,  6]])

## Sorting

In [25]:
x = np.array([ [4,3,5], [1,2,1] ])
x

array([[4, 3, 5],
       [1, 2, 1]])

#### Sort by Column (axis=0)

In [26]:
#Sort by column
np.sort(x, axis=0)

array([[1, 2, 1],
       [4, 3, 5]])

#### Sort by Rows (axis=1)

In [27]:
y = np.sort(x, axis=1)
y

array([[3, 4, 5],
       [1, 1, 2]])

In [28]:
#Sorts the View in place
y

array([[3, 4, 5],
       [1, 1, 2]])

#### Does NOT Sort Original Array

In [29]:
#Original Array stays the same
x

array([[4, 3, 5],
       [1, 2, 1]])

## Indecies of Sorted Array

In [30]:
arr = np.array([4,3,1,2])
arr

array([4, 3, 1, 2])

#### Get Array of Indecies of Sorted Array

In [31]:
arr_idx = np.argsort(arr)
arr_idx

array([2, 3, 1, 0], dtype=int64)

#### Sort Based on Array of Indecies

In [32]:
arr[arr_idx]

array([1, 2, 3, 4])

#### Original Array Stays the Same

In [33]:
arr

array([4, 3, 1, 2])