# NumPy - Operations

In [73]:
import numpy as np

## Element-wise Operations

In [74]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [75]:
a = a**2
a

array([ 1,  4,  9, 16])

In [76]:
#Add 1 to each element
b = np.ones(4) + 1
b

array([ 2.,  2.,  2.,  2.])

In [77]:
#Subtract by element
a - b

array([ -1.,   2.,   7.,  14.])

In [78]:
#Multiply element by element
a * b

array([  2.,   8.,  18.,  32.])

## Matrix operations

#### Create Array 

In [79]:
m = np.ones((3,3)) + np.array([1,2,3])
m

array([[ 2.,  3.,  4.],
       [ 2.,  3.,  4.],
       [ 2.,  3.,  4.]])

#### Regular Multiplication - NOT Matrix mMultiplication
Multiply each element by each other

In [80]:
m * m

array([[  4.,   9.,  16.],
       [  4.,   9.,  16.],
       [  4.,   9.,  16.]])

#### Use dot() function for Matrix Multiplication

In [81]:
m.dot(m)

array([[ 18.,  27.,  36.],
       [ 18.,  27.,  36.],
       [ 18.,  27.,  36.]])

In [82]:
#Same as above
np.dot(m,m)

array([[ 18.,  27.,  36.],
       [ 18.,  27.,  36.],
       [ 18.,  27.,  36.]])

## Comparison

#### Comparing Elements of Arrays

In [83]:
x = np.array([1,2,3,4])
y = np.array([4,2,2,4])

In [84]:
#Creates Boolean Array
z = x == y
z

array([False,  True, False,  True], dtype=bool)

In [85]:
z = x > y
z

array([False, False,  True, False], dtype=bool)

#### Comparing Whole Array

In [86]:
w = np.array([1,2,3,4])

In [87]:
np.array_equal(x,y)

False

In [88]:
np.array_equal(x,w)

True

## Sum

#### 1-D Array - add all elements together

In [89]:
c = np.array([1,2,3,4])
c.sum()

10

#### 2-D Array - add by column to get 1-D array (axis=0)

In [90]:
d = np.array([ [1,1], [2,2] ])
d

array([[1, 1],
       [2, 2]])

In [91]:
d.sum(axis=0)

array([3, 3])

In [92]:
#same as above
column_array = ( d[:,0].sum(), d[:,1].sum() )
column_array

(3, 3)

#### 2-D Array - add by row to get 1-D array (axis=1)

In [93]:
#Add by row to get 1-D Array
d.sum(axis=1)

array([2, 4])

In [94]:
#same as above
row_array = (d[0,:].sum(), d[1,:].sum())
row_array

(2, 4)

## Working with Mismatch Shapes

#### Value Error when adding Missmatched arrays

In [103]:
c = np.arange(4)
d = np.array([1,2])

In [107]:
try:
    c + d
except ValueError as e:
    print("Can't add arrays of different shapes: " + str(e))

Can't add arrays of different shapes: operands could not be broadcast together with shapes (4,) (2,) 


## Broadcasting - arithmetic operations on arrays with different shapes

### Create 2-D Array of repeated data - using tile()
Tile (3,1) means repeat it for 3 rows, 1 time

In [97]:
a = np.tile(np.arange(0,40,10), (3,1))
a

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [98]:
#Same as above - Repeat a for 3 rows and only 1 column
a = np.arange(0,40,10)
a = np.tile(a, (3,1))
a

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [99]:
#Tile (2,2) means repeat it for 2 rows 2 times
a = np.tile(np.arange(0,40,10), (2,2))
a

array([[ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30]])

#### Transpose Array - .T is the same as transpose()

In [100]:
a = np.tile(np.arange(0,40,10), (3,1)).T
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [117]:
b = np.array([0,1,2])
b

array([0, 1, 2])

#### Add element by Element - Broadcasting (Rows or Columns have to match)

In [118]:
print(a.shape)
print(b.shape)
a + b

(4, 3)
(3,)


array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])