# NumPy - Mask

In [2]:
import numpy as np

### Using Mask to select elements of Array

#### Seeding to produce same random numbers

In [12]:
np.random.seed(3)

#### Create an Array of 15 Random Integers ranging from 0 to 20

In [13]:
#Deprecated way -> np.random.random_integers(0, 20, 15)
a3 = np.random.randint(0,20,15)
a3

array([10,  3,  8,  0, 19, 10, 11,  9, 10,  6,  0, 12,  7, 14, 17])

#### Creates Boolean Array of True and False, based on condition of the initial Array

In [14]:
a3 % 3 == 0

array([False,  True, False,  True, False, False, False,  True, False,
        True,  True,  True, False, False, False], dtype=bool)

#### Use mask to extract elements based on the mask condition

In [15]:
mask = (a3 % 3 == 0) #Creates the boolean Array
extract_from_a3 = a3[mask]
extract_from_a3

array([ 3,  0,  9,  6,  0, 12])

In [16]:
#Same as above in one line
a3[a3%3==0]

array([ 3,  0,  9,  6,  0, 12])

#### Assign values based on the Mask

In [17]:
a3[a3%3==0] = -1
a3

array([10, -1,  8, -1, 19, 10, 11, -1, 10, -1, -1, -1,  7, 14, 17])

## Could use any condition in mask - applies to each element 

In [18]:
# array, where array element is condition
a3[a3 < 10]

array([-1,  8, -1, -1, -1, -1, -1,  7])

In [19]:
a3[a3+2 < 10]

array([-1, -1, -1, -1, -1, -1,  7])