# NumPy - Indexing

In [1]:
import numpy as np

## Indexing 1-D Array

#### Create Array

In [2]:
x1 = np.array([8,0,5,2,7,9])

#### Get First Element

In [3]:
x1[0]

8

#### Get Last Element

In [4]:
x1[-1]

9

## Indexing 2-D Array

In [5]:
x2 = np.array([ (2,4,6), (3,6,9), (4,8,12) ])
x2

array([[ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12]])

In [6]:
#First element
x2[0,0]

2

In [7]:
#Can also use separate brackets
x2[0][1]

4

In [8]:
#Last element
x2[-1,-1]

12

In [9]:
#Second row, First column
x2[1,0]

3

## Reverse Array

In [10]:
rev_array = np.arange(10)
rev_array[::-1] #same as 0 to end going by -1

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Indexing with Skips

#### Create 1-D Array

In [11]:
y1 = np.arange(6)
y1

array([0, 1, 2, 3, 4, 5])

#### Create anothe 1-D array and reshape it into 2-D

In [12]:
y2 = np.arange(0,51,10).reshape(6,1)
y2

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50]])

#### Add 2 Arrays together

In [13]:
y3 = y1 + y2
y3

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

#### Get Sub-Array
from row 3 to end with 2 steps (skipping row), 
from begining column to end with step 2

In [14]:
y3[2::2,::2] #from row[2] to end skip by 2 -> 2::2,  from this matrix from begginig to end :: skip by 2 -> ::2

array([[20, 22, 24],
       [40, 42, 44]])

## Sub-array Returns a View
Changes to sub array will affect origianl array

#### Using 2-D Array

In [15]:
arr = np.array([ [0,1], [2,3], [4,5], [6,7] ])
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

#### This will return a sub array BUT only a view

In [16]:
sub_arr = arr[0:2,0:2]
sub_arr

array([[0, 1],
       [2, 3]])

#### Test to see if it's a view

In [17]:
sub_arr.base is arr

True

#### Modify the View

In [18]:
sub_arr[:,:] = np.zeros((2,2))
sub_arr

array([[0, 0],
       [0, 0]])

#### Changes in Sub-Array affect Original Array

In [19]:
arr

array([[0, 0],
       [0, 0],
       [4, 5],
       [6, 7]])

## Changing values in Array

In [20]:
a = np.array([ [10,20], [30,40], [50,60] ])
a

array([[10, 20],
       [30, 40],
       [50, 60]])

#### Return first row view

In [21]:
a[0]

array([10, 20])

#### Change all elements in first row to 1

In [22]:
a[0] = 1
a

array([[ 1,  1],
       [30, 40],
       [50, 60]])

#### Change First element to 16

In [23]:
a[0][0] = 16
a

array([[16,  1],
       [30, 40],
       [50, 60]])

#### Get all elements from second row

In [24]:
a[1:]

array([[30, 40],
       [50, 60]])

In [25]:
#Same as above - All from second row, All columns
a[1:, :]

array([[30, 40],
       [50, 60]])

#### Change all elements from second row to 10

In [26]:
a[1:, :] = 10
a

array([[16,  1],
       [10, 10],
       [10, 10]])

#### Assign new values to new sub-array.  Make sure it's same shape as sub-array

In [27]:
a[1:, :] = ([10, 20], [30,40])
a

array([[16,  1],
       [10, 20],
       [30, 40]])